version: '2'
services:
  grace-server:
    build:
      context: ./packages/backend
    ports:
      - "5000:3000"
    networks:
      - default
    restart: on-failure
    mem_limit: 4000m

  grace-web:
    build: 
      context: ./packages/frontend
    ports:
      - "3000:3000"
    environment: 
      - REACT_APP_SERVER=http://localhost:5000 
    networks:
      - default
    depends_on:
      - grace-server
    restart: on-failure
    mem_limit: 2000m
